name: location_agent
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the m ajor, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+37
# for ios
# version: 1.0.12+25


environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_offline: ^2.1.0
  animated_text_kit: ^4.2.2
  email_validator: ^2.1.17
  google_fonts: ^3.0.1
  bot_toast: ^4.0.3
  shared_preferences: ^2.0.15
  bordered_text: ^2.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  # image_picker: ^0.8.6
  modal_bottom_sheet: ^2.1.2
  flutter_credit_card: ^3.0.4
  # qr_flutter: ^4.0.0
  url_launcher: ^6.1.7
  toast: ^0.3.0
  animator: ^3.0.0
  lottie: ^2.2.0
  provider: ^6.0.5
  adaptive_theme: ^3.1.1
  flutter_switch: ^0.3.2
  get: ^4.6.5
  intl_phone_field: ^3.1.0
  http: ^0.13.5
  flutter_localization: ^0.1.9
  roundcheckbox: ^2.0.5
  package_info_plus: ^3.0.2
  firebase_core: ^2.4.1
  country_picker: ^2.0.19
  flutter_otp_text_field: ^1.1.1
  share_plus: ^6.3.1
  firebase_storage: ^11.0.14
  # face_camera: ^0.0.6
  path_provider: ^2.0.9
  camera: ^0.9.4+21
  camerawesome: ^1.2.1
  better_open_file: ^3.6.4
  # webview_flutter: ^0.3.0
  webview_flutter: ^4.0.2
  # flutter_image_compress: ^1.1.3
  dio_http_cache: ^0.3.0
  # flutter_native_image: ^0.0.6+1

  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  flutter_native_image: ^0.0.6+1
  auto_layout: ^1.0.5
  custom_qr_generator: ^0.1.1
  shimmer: ^3.0.0
  fl_chart: ^0.40.0
  percent_indicator: ^4.2.3
  # flutter_barcode_scanner: ^2.0.0

  mac_address: ^1.0.0
  device_imei: ^0.0.1
  device_info_plus: ^8.2.2
  macadress_gen: ^0.0.4
  device_information: ^0.0.4
  unique_identifier: ^0.3.0

  google_maps_flutter: ^2.0.6
  geolocator: ^9.0.2
  permission_handler: ^9.2.0
  
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/icons/trajet-trans.svg
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages