part of 'signup_cubit.dart';

class SignupState {
  Map? field;
  SignupState({required this.field});
}

Map? initialState() {
  return {
    'idAgent': "",
    'idUser': "",
    'nom': "",
    'postnom': "",
    'prenom': "",
    'descProduit': "",
    'volumeProduit': "",
    'prixProduit': "",
    'qteProduit': "",
    'provinceDataKelasi': [],
    'villeDataKelasi': [],
    'communeDataKelasi': [],
    'provinceKelasi': "",
    'universiteData': [],
    'provinceData': [],
    'villeData': [],
    'communeData': [],
    "universite": "",
    'faculteData': [],
    'faculte': "",
    'departementData': [],
    'departement': "",
    'promotionData': [],
    'ecoleData': [],
    'productData': [],
    'productDataBySite' : [],
    'volumeData': [],
    'operationData' : [],
    'operationreasonData' : [],
    'siteData': [],
    'ligneCommande': [],
    'siteAgent' : "",
    'operationnature' : "",
    'operationreason' : "",
    'product': "",
    'productBySite' : "",
    'PrixProductVendu' : "",
    'volume': "",
    'idsite': "",
    'quantiteProduit': "",
    'descriptionProduit': "",
    'nomsite': "",
    'dateaffectation' : "",
    'localisationsite': "",
    'promotion': "",
    'currency': "",
    'phone': "",
    'phonePayment': "",
    'matricule': "",
    'password': "",
    'confirmPassword': "",
    'sexe': "",
    'dateNaissance': "",
    'commune': "",
    'quartier': "",
    'avenue': "",
    'numeroAdresse': "",
    'province': "",
    'numeroTelephone': "",
    'email': "",
    'lieuNaissance': "",
    'codeEtudiant': "",
    'typePayment': "",
    'iconVersion': "",
    'titreVersion': "",
    'course': "",
    'date': "",
    'filePath': "",
    'photo': "",
    'imageCourse': "",
    'prixUSD': "",
    'prixCDF': "",
    'selectedIndex': "",
    'status': "",
    'typePaymentFromApi': "",
    'abonnement': "",
    'code': "",
    'refresh': "",
    'day': "",
    'hours': "",
    'valueAbonnement': "",
    'descriptionVersion': "",
    'disponibility': "",
    'inputVisible': "",
    'codetransaction': "",
    "kelasiActiveIndex": "",
    "ecole": "",
    "sectionData": [],
    "section": "",
    "optionData": [],
    "option": "",
    "levelData": [],
    "level": "",
    "userId": "",
    "parentId": "",
    "fromSingup": "false",
    "nomsiteError": "",
    "localisationsiteError": "",
    "nomError": "",
    "descProduitError": "",
    'prixProduitError': "",
    'qteProduitError': "",
    "postnomError": "",
    "prenomError": "",
    "emailError": "",
    "passwordError": "",
    "confirmPasswordError": "",
    "nombreEnfant": "",
    'slides': [
      {
        "_id": "641056cb5792d792918755a4",
        "url":
            "https://firebasestorage.googleapis.com/v0/b/trans-academia.appspot.com/o/profiles%2Fcarousel-1.jpeg?alt=media&token=51501e3d-f04d-4382-8329-015c45e8cf95",
        "title": "slide 1",
        "createdAt": "2023-03-14T11:13:15.947Z",
        "updatedAt": "2023-03-14T11:13:15.947Z",
        "__v": 0
      },
    ]
  };
}
